### ISSUE TITLE
Something got broken...

### ISSUE THREAD

**Issue by jomo666** [mamod/JavaScript-Duktape#17]
I just tried to install `JavsScript::Duktape` again in some new machine, using `plenv` with perl `5.24.0-RC1`. The `JavsScript::Duktape` is got installed OK without any errors nor warnings.

But when tried the example code, from the `Synopsys`: e.g.

```
use strict;
use warnings;
use JavaScript::Duktape;

##create new js context
my $js = JavaScript::Duktape->new();

#set function to be used from javascript land
$js->set('write' => sub {
    my $duk = shift;
    print $_[0], "\n";
});

$js->eval(qq~
        for (var i = 0; i < 100; i++){
            write(i);
        }
~);
```

It prints only 100 empty lines and got100 warnings:

```
Use of uninitialized value in print at d line 11.
```

so the `print $_[0], "\n";` isn't works.

Could be this somewhat perl-version specific, or something is changed in the `JavaScript::Duktape`? (In such case probably need change the example code in the `Synopsys`).

Any idea how to make the above code work again with perl `5.24.0-RC1`?

**Comment by jomo666** [comment]
Ahhh... just found in the the changelog:

```
        - deprecate passing duk instance as first argument to functions
```

deleting the line

```
    my $duk = shift;
```

make it work again. Definitely it's not a bug - just needs upgrade the docs only :) :)

**Comment by mamod** [comment]
oops my mistake, I forgot to update the docs.
JavaScript::Duktape is v1.0.0 with stable API now

I'm going to update the docs,  thanks for the heads-up :+1:

**Comment by mamod** [comment]
fixed the docs, thanks again :)

**Comment by jomo666** [comment]
Thank you and sorry that I bugged you with such trifling thing...
