### ISSUE TITLE
t/dll.t may segfault

### ISSUE THREAD

**Issue by eserte** [mamod/JavaScript-Duktape#29]
On some of my smoker systems t/dll.t just fails:
```
t/dll.t ........................... 
No subtests run 
```
The test summary suggests that a segmenation fault happened here:
```
t/dll.t                         (Wstat: 11 Tests: 0 Failed: 0)
  Non-zero wait status: 11
```
I don't see a pattern in the affected perl versions or operating systems --- I see fails for some combinations of  perl 5.22.1 .. 5.26.0 and debian jessie, debian stretch, CentOS7, Ubuntu 16.04.

**Comment by mamod** [comment]
@eserte thank you for reporting this and sorry for the delay, I disabled this test in fbde061c229277c366f4af8e774e8ec47e82d960

at the moment this feature is not documented and error prone so I kept it for development purposes and maybe future implementation.

Thank you again
