### ISSUE TITLE
alert and print are undocumented

### ISSUE THREAD

**Issue by cpansprout** [mamod/JavaScript-Duktape#31]
I discovered by accident that JavaScript::Duktape installs ‘alert’ and ‘print’ functions into the JavaScript environment without documenting them at all.

This should be documented, so that someone trying to run JavaScript code in a restricted environment will not be providing JS code with unintended capabilities.

An option to disable these bindings would also be nice.

**Comment by mamod** [comment]
@cpansprout thank you, I just added a note about these 2 functions in docs see 8ca49a06ceb58c9945e6c95cd50721ecfb294bae
