### ISSUE TITLE
strange try-tiny interaction results in blank $@

### ISSUE THREAD

**Issue by rodrigolive** [mamod/JavaScript-Duktape#9]
The problem here is that a try-catch wrapped `$js->eval()` will not get the error message rethrown in the `catch { die $err }`. 

This did not occur with v0.3.0, only with the new error correction pushed to the `master` branch.

Here's the code:

```
use strict;
use warnings;
use JavaScript::Duktape;
use Try::Tiny;

try {
    eval_js(q{
        throw new Error('oh boy!');
    });
} catch {
    my $err = shift;
    warn "TRY-TINY ERR=$err"; #### $err is blank!?!
};

eval {
    eval_js(q{
        throw new Error('oh boy!');
    });
};
warn "EVAL ERR=$@"; ###### blank again!?!

sub eval_js {
    my $code = shift;

    my $js= JavaScript::Duktape->new;

    try {
        $js->eval( $code );
    } catch {
        my $err = $_;
        warn "CAUGHT ERR: $err";
        die "JS ERR: $err";
    };
}
```

**Comment by mamod** [comment]
Thanks again, I'm looking at this right now :)

**Comment by mamod** [comment]
:+1: for spotting this really strange behavior, fixed with #10 but need more investigation to know why this happened at first place!!

**Comment by rodrigolive** [comment]
Thanks Mamod, now it passes the try-tiny test case, but strangely it still doesn't work in my app, which has maybe a few more levels of try's and/or eval's... 

Anyway I'll just use it with `eval{ .. }` for now as an workaround. Hopefully your "CSI investigation" finds the root cause. :) 

Are you pushing this out to CPAN soon? I think 1.0.0 is a nice version to share with the world.

**Comment by mamod** [comment]
Yes, I will wrap it for CPAN very soon maybe in the next couple of days, but I need to fix this behavior first and write some more documents :)

Can you please test against [finalizer_bug](https://github.com/mamod/JavaScript-Duktape/tree/finalizer_bug) branch, this will be very helpful :)

Thank you for your time and help.

**Comment by rodrigolive** [comment]
My app passes all tests with the finalizer_bug branch, oh yes.

**Comment by mamod** [comment]
Great, now I guess I have a better idea of what's going on :)

It seems that duktape heap destruction messes with perl $@ var.
I will also fix some other related issues regarding localizing $@ and release to CPAN

can you please test from _v1.0.0_6_ branch, this should be fixed for good now :)

**Comment by rodrigolive** [comment]
I have something else that worked in v.0.3.0 and now in your v1.0.0_6 stopped working: evalling the Typescript.js library gives a strange "not number" error and spurious segmentation faults. 

I'm adding it as a test case. I know having typescript.js as part of your test suite is not ideal, but it's just one file and other people in the Duktape community never had any problems with it (except for a rogue regex that needs to be changed). It's a good compile stress-test.

**Comment by rodrigolive** [comment]
Ups, it's the duktape library version. Updating to 1.3.2 might be a good idea. Pushing it to the pull request #13

**Comment by mamod** [comment]
@rodrigolive Regarding blank error var $@, is it resolved with your app tests or should I reopen?

typescript tests is great thanks :+1:

**Comment by rodrigolive** [comment]
Everything working just great, try-catch is working nice. Just added babel and coffeescript transpiling to my app and must say everything works like a clock. Great job!

**Comment by mamod** [comment]
I'm really glad it's working now and thank you very much for your time and contribution :)
please let me know if any issue arises.

**Comment by rodrigolive** [comment]
Hey Mamod, when are you planning to release 1.0.0 to CPAN? I'm eager to install it the official way. 
thanks!

**Comment by mamod** [comment]
@rodrigolive I'm on it tonight, I'll issue a release first thing tomorrow morning :)

**Comment by mamod** [comment]
@rodrigolive sorry for the delay, it's now uploaded to cpan, please don't hesitate to report any issue you find :)

thank you very much for your contributions :+1:
